# Generated by Django 5.1.15 on 2026-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_history_team1_match_history_team2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='history_team1',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='history_team2',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
