# Generated by Django 5.1.15 on 2026-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_match_history_team1_alter_match_history_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
    ]
