# Generated by Django 5.1.15 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_match_is_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='table_count',
            field=models.IntegerField(default=2),
        ),
    ]
